# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "https://salemdynamics.com"

[_.globalMeta]
title = "Salem Dynamics"
description = "Small, local web business."
longDescription = "Small web design business created by a man and his cat."
cardImage = "https://salemdynamics.com/Salem.webp"
keywords = ["web development", "design", "technology"]

[_.blogMeta]
title = "Salem Dynamics Blog"
description = "Practical wisdom, unfiltered thoughts, and hot takes."
longDescription = "Web development, tech trends, and the occasional programming mishap."
cardImage = "https://salemdynamics.com/Salem.webp"
keywords = ["web development", "design", "technology"]

[_.projectMeta]
title = "Salem Dynamics Projects"
description = "A list of my web development projects and developer tools."
longDescription = "All of my projects, including both frontend and full-stack applications."
cardImage = "https://salemdynamics.com/Salem.webp"
keywords = ["web development", "design", "technology"]

[_.notFoundMeta]
title = "Salem Dynamics 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."
cardImage = "https://salemdynamics.com/Salem.webp"

[_.hero]
title = "Salem Dynamics"
subtitle = "Small, local web business<br />created by a man and his cat."
image = "https://salemdynamics.com/Salem.webp"
ctaText = "View Projects"
ctaUrl = "/projects"

[_.personal]
name = "Salem Dynamics"
githubProfile = "https://github.com/iudexus"
twitterProfile = "https://twitter.com"
linkedinProfile = "https://linkedin.com/"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"